project:
  type: website
  output-dir: docs

website:
  title: "Egzaminy"
  navbar:
    left:
      - text: "Losowanie"
        href: index.qmd
      - text: "Eksploracja danych"
        href: Pytania_eksploracja.qmd
      - text: "Eksploracja danych - abstrakt"
        href: Pytania_eksploracja_skrot.qmd
      - text: "Testowe"
        href: analizaII.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

