project:
  type: website
  output-dir: docs

website:
  title: "Egzaminy"
  navbar:
    left:
      - text: "Losowanie"
        href: index.qmd
      - text: "Eksploracja danych"
        href: Pytania_eksploracja.qmd
      - text: "Metody walidacji"
        href: Pytania_walidacja.qmd
      - text: "Ekonometria"
        href: ekonometria.qmd
      # - text: "Eksploracja danych - abstrakt"
      #   href: Pytania_eksploracja_skrot.qmd
      # - text: "Eksploracja danych - streszczenie"
      #   href: Pytania_eksploracja_skrot2.qmd
      # - text: "Testowe"
      #   href: analizaII.qmd
      - text: "Metody numeryczne"
        href: numeryczne.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

